# Generated by Django 5.2.7 on 2025-10-21 16:46

from django.db import migrations


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vacaciones', '0003_alter_solicitudvacaciones_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
            ],
            options={
                'verbose_name': 'Feriado',
                'verbose_name_plural': 'Feriados',
                'ordering': ['fecha'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('vacaciones.feriado',),
        ),
    ]
