# Generated by Django 5.2.7 on 2025-10-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='horario',
            name='dias_laborables_mask',
            field=models.PositiveSmallIntegerField(default=62, help_text='Bitmask: 1<<0=Dom, 1<<1=Lun, ... 1<<6=Sáb (por defecto L-V).'),
        ),
    ]
