# Generated by Django 5.2.7 on 2025-10-21 16:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogos', '0002_horario_dias_laborables_mask'),
        ('empleados', '0002_empleado_usuario_historicalempleado_usuario'),
        ('organigrama', '0002_ubicacion_organigrama_nombre_ef2923_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['estatus'], name='empleados_e_estatus_4edbd0_idx'),
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['unidad_negocio', 'sucursal'], name='empleados_e_unidad__495414_idx'),
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['area', 'departamento'], name='empleados_e_area_id_c5b030_idx'),
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['puesto'], name='empleados_e_puesto__acd279_idx'),
        ),
        migrations.AddIndex(
            model_name='empleado',
            index=models.Index(fields=['usuario'], name='empleados_e_usuario_620b75_idx'),
        ),
    ]
