# Generated by Django 5.2.7 on 2025-10-18 03:43

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sucursal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=32, unique=True)),
                ('nombre', models.CharField(db_index=True, max_length=255)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('codigo_postal', models.CharField(blank=True, default='', max_length=10)),
                ('ciudad', models.CharField(blank=True, default='', max_length=128)),
                ('estado', models.CharField(blank=True, default='', max_length=128)),
                ('direccion', models.CharField(blank=True, default='', max_length=255)),
                ('telefono', models.CharField(blank=True, default='', max_length=32)),
            ],
            options={
                'verbose_name': 'Sucursal',
                'verbose_name_plural': 'Sucursales',
                'ordering': ('nombre',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='UnidadNegocio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=32, unique=True)),
                ('nombre', models.CharField(db_index=True, max_length=255)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Unidad de negocio',
                'verbose_name_plural': 'Unidades de negocio',
                'ordering': ('nombre',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave', models.CharField(max_length=32, unique=True)),
                ('nombre', models.CharField(db_index=True, max_length=255)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='subareas', to='organigrama.area')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='areas', to='organigrama.sucursal')),
            ],
            options={
                'verbose_name': 'Área',
                'verbose_name_plural': 'Áreas',
                'ordering': ('nombre',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ubicacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('lon', models.DecimalField(decimal_places=6, max_digits=9, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('radio_m', models.PositiveIntegerField(default=100, help_text='Radio de geocerca en metros (mínimo 10)', validators=[django.core.validators.MinValueValidator(10)])),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('area', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ubicaciones', to='organigrama.area')),
                ('sucursal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ubicaciones', to='organigrama.sucursal')),
            ],
            options={
                'verbose_name': 'Ubicación',
                'verbose_name_plural': 'Ubicaciones',
                'ordering': ('nombre',),
            },
        ),
        migrations.AddField(
            model_name='sucursal',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sucursales', to='organigrama.unidadnegocio'),
        ),
        migrations.AddIndex(
            model_name='area',
            index=models.Index(fields=['sucursal', 'nombre'], name='organigrama_sucursa_0cf38d_idx'),
        ),
        migrations.AddConstraint(
            model_name='area',
            constraint=models.UniqueConstraint(fields=('sucursal', 'clave'), name='uniq_area_clave_por_sucursal'),
        ),
        migrations.AddIndex(
            model_name='ubicacion',
            index=models.Index(fields=['activo', 'sucursal', 'area'], name='organigrama_activo_7ca6b0_idx'),
        ),
    ]
