# Generated by Django 5.2.7 on 2025-10-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organigrama', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='ubicacion',
            index=models.Index(fields=['nombre'], name='organigrama_nombre_ef2923_idx'),
        ),
        migrations.AddConstraint(
            model_name='ubicacion',
            constraint=models.CheckConstraint(condition=models.Q(('sucursal__isnull', False), ('area__isnull', False), _connector='OR'), name='ubicacion_owner_requerido'),
        ),
        migrations.AddConstraint(
            model_name='ubicacion',
            constraint=models.UniqueConstraint(condition=models.Q(('sucursal__isnull', False)), fields=('sucursal', 'nombre'), name='uniq_ubicacion_por_sucursal_nombre'),
        ),
        migrations.AddConstraint(
            model_name='ubicacion',
            constraint=models.UniqueConstraint(condition=models.Q(('area__isnull', False)), fields=('area', 'nombre'), name='uniq_ubicacion_por_area_nombre'),
        ),
    ]
