# Generated by Django 5.2.7 on 2025-10-18 05:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0002_empleado_usuario_historicalempleado_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoPermiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=120, unique=True)),
                ('con_goce', models.BooleanField(default=False)),
                ('requiere_evidencia', models.BooleanField(default=False)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Permiso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('horas', models.DecimalField(blank=True, decimal_places=2, help_text='Opcional para medio día / horas', max_digits=5, null=True)),
                ('motivo', models.CharField(blank=True, default='', max_length=255)),
                ('evidencia', models.FileField(blank=True, null=True, upload_to='permisos/evidencia/')),
                ('estado', models.CharField(choices=[('PEND', 'Pendiente'), ('APROB', 'Aprobado'), ('RECH', 'Rechazado'), ('CANC', 'Cancelado')], db_index=True, default='PEND', max_length=5)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('aprobado_en', models.DateTimeField(blank=True, null=True)),
                ('comentario_aprobador', models.CharField(blank=True, default='', max_length=255)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permisos_aprobados', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='permisos_creados', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permisos', to='empleados.empleado')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='permisos', to='permisos.tipopermiso')),
            ],
            options={
                'ordering': ('-creado_en',),
                'indexes': [models.Index(fields=['empleado', 'estado', 'fecha_inicio', 'fecha_fin'], name='permisos_pe_emplead_458444_idx')],
            },
        ),
    ]
