# Generated by Django 5.2.7 on 2025-10-19 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tipopermiso',
            options={'ordering': ('nombre',)},
        ),
    ]
