# Generated by Django 5.2.7 on 2025-10-21 16:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_empleado_empleados_e_estatus_4edbd0_idx_and_more'),
        ('permisos', '0002_alter_tipopermiso_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='permiso',
            options={'ordering': ('-creado_en',), 'verbose_name': 'Permiso', 'verbose_name_plural': 'Permisos'},
        ),
        migrations.AlterModelOptions(
            name='tipopermiso',
            options={'ordering': ('nombre',), 'verbose_name': 'Tipo de permiso', 'verbose_name_plural': 'Tipos de permiso'},
        ),
        migrations.AlterField(
            model_name='permiso',
            name='estado',
            field=models.CharField(choices=[('PEND', 'Pendiente'), ('APROB', 'Aprobada'), ('RECH', 'Rechazada'), ('CANC', 'Cancelada')], db_index=True, default='PEND', max_length=5),
        ),
        migrations.AddIndex(
            model_name='permiso',
            index=models.Index(fields=['empleado', 'estado'], name='permisos_pe_emplead_f890a6_idx'),
        ),
        migrations.AddIndex(
            model_name='permiso',
            index=models.Index(fields=['tipo'], name='permisos_pe_tipo_id_90d44c_idx'),
        ),
        migrations.AddIndex(
            model_name='permiso',
            index=models.Index(fields=['fecha_inicio'], name='permisos_pe_fecha_i_3e850e_idx'),
        ),
        migrations.AddIndex(
            model_name='permiso',
            index=models.Index(fields=['fecha_fin'], name='permisos_pe_fecha_f_efaaef_idx'),
        ),
        migrations.AddConstraint(
            model_name='permiso',
            constraint=models.CheckConstraint(condition=models.Q(('horas__isnull', True), ('horas__gte', 0), _connector='OR'), name='perm_horas_no_negativas'),
        ),
        migrations.AddConstraint(
            model_name='permiso',
            constraint=models.CheckConstraint(condition=models.Q(('horas__isnull', True), ('fecha_inicio', models.F('fecha_fin')), _connector='OR'), name='perm_horas_un_solo_dia'),
        ),
        migrations.AddConstraint(
            model_name='permiso',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin__gte', models.F('fecha_inicio'))), name='perm_rango_fechas_valido'),
        ),
    ]
