# Generated by Django 5.2.7 on 2025-10-18 04:09

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0002_empleado_usuario_historicalempleado_usuario'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feriado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(unique=True)),
                ('nombre', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ('fecha',),
            },
        ),
        migrations.CreateModel(
            name='PoliticaVacaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anios_desde', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('anios_hasta', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('dias', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(365)])),
                ('arrastre_maximo', models.PositiveSmallIntegerField(default=0, help_text='Días que se pueden arrastrar al siguiente año')),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Política de vacaciones',
                'verbose_name_plural': 'Políticas de vacaciones',
                'ordering': ('anios_desde',),
                'constraints': [models.CheckConstraint(condition=models.Q(('anios_hasta__gte', models.F('anios_desde'))), name='rango_valido')],
            },
        ),
        migrations.CreateModel(
            name='BalanceVacaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anio', models.PositiveIntegerField()),
                ('dias_asignados', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('dias_arrastrados', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('dias_tomados', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('dias_disponibles', models.DecimalField(decimal_places=2, default=0, max_digits=6)),
                ('caduca_el', models.DateField(blank=True, null=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='balances_vac', to='empleados.empleado')),
            ],
            options={
                'ordering': ('empleado', '-anio'),
                'unique_together': {('empleado', 'anio')},
            },
        ),
        migrations.CreateModel(
            name='SolicitudVacaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
                ('dias', models.DecimalField(decimal_places=2, help_text='Días hábiles calculados', max_digits=6)),
                ('motivo', models.CharField(blank=True, default='', max_length=255)),
                ('estado', models.CharField(choices=[('PEND', 'Pendiente'), ('APROB', 'Aprobada'), ('RECH', 'Rechazada'), ('CANC', 'Cancelada')], db_index=True, default='PEND', max_length=5)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('aprobado_en', models.DateTimeField(blank=True, null=True)),
                ('comentario_aprobador', models.CharField(blank=True, default='', max_length=255)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sol_vac_aprobadas', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sol_vac_creadas', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_vac', to='empleados.empleado')),
            ],
            options={
                'ordering': ('-creado_en',),
                'indexes': [models.Index(fields=['empleado', 'estado', 'fecha_inicio', 'fecha_fin'], name='vacaciones__emplead_f746f1_idx')],
            },
        ),
    ]
