# Generated by Django 5.2.7 on 2025-10-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0002_empleado_usuario_historicalempleado_usuario'),
        ('vacaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='politicavacaciones',
            name='rango_valido',
        ),
        migrations.AlterField(
            model_name='solicitudvacaciones',
            name='estado',
            field=models.CharField(choices=[('PEND', 'Pendiente'), ('APROB', 'Aprobado'), ('RECH', 'Rechazado'), ('CANC', 'Cancelado')], db_index=True, default='PEND', max_length=5),
        ),
        migrations.AddIndex(
            model_name='balancevacaciones',
            index=models.Index(fields=['empleado', 'anio'], name='vacaciones__emplead_649d31_idx'),
        ),
        migrations.AddConstraint(
            model_name='politicavacaciones',
            constraint=models.CheckConstraint(condition=models.Q(('anios_hasta__gte', models.F('anios_desde'))), name='vac_politica_rango_valido'),
        ),
    ]
