# Generated by Django 5.2.7 on 2025-10-21 16:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empleados', '0003_empleado_empleados_e_estatus_4edbd0_idx_and_more'),
        ('vacaciones', '0002_remove_politicavacaciones_rango_valido_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='solicitudvacaciones',
            options={'ordering': ('-fecha_inicio', '-creado_en')},
        ),
        migrations.AddField(
            model_name='solicitudvacaciones',
            name='comentario',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='solicitudvacaciones',
            name='dias_habiles',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='solicitudvacaciones',
            name='resuelto_en',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='solicitudvacaciones',
            name='resuelto_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacaciones_resueltas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='solicitudvacaciones',
            name='dias',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Días hábiles calculados (legacy decimal, sincronizado con dias_habiles).', max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='solicitudvacaciones',
            name='estado',
            field=models.CharField(choices=[('PEND', 'Pendiente'), ('APROB', 'Aprobada'), ('RECH', 'Rechazada'), ('CANC', 'Cancelada')], db_index=True, default='PEND', max_length=5),
        ),
        migrations.AddIndex(
            model_name='solicitudvacaciones',
            index=models.Index(fields=['empleado', 'estado'], name='vacaciones__emplead_6ec926_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudvacaciones',
            index=models.Index(fields=['fecha_inicio'], name='vacaciones__fecha_i_8a8be2_idx'),
        ),
        migrations.AddIndex(
            model_name='solicitudvacaciones',
            index=models.Index(fields=['fecha_fin'], name='vacaciones__fecha_f_aa64d8_idx'),
        ),
        migrations.AddConstraint(
            model_name='solicitudvacaciones',
            constraint=models.CheckConstraint(condition=models.Q(('fecha_fin__gte', models.F('fecha_inicio'))), name='vac_sol_rango_valido'),
        ),
        migrations.AddConstraint(
            model_name='solicitudvacaciones',
            constraint=models.CheckConstraint(condition=models.Q(('dias_habiles__gte', 0)), name='vac_sol_dias_habiles_no_negativos'),
        ),
        migrations.AddConstraint(
            model_name='solicitudvacaciones',
            constraint=models.CheckConstraint(condition=models.Q(('dias__isnull', True), ('dias__gte', 0), _connector='OR'), name='vac_sol_dias_legacy_no_negativos'),
        ),
    ]
