# Generated by Django 5.2.7 on 2025-10-18 03:57

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('empleados', '0001_initial'),
        ('organigrama', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Checada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida')], max_length=3)),
                ('ts', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('fuente', models.CharField(choices=[('MOBILE', 'Móvil'), ('WEB', 'Web'), ('KIOSK', 'Kiosco'), ('OTHER', 'Otro')], default='MOBILE', max_length=10)),
                ('lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90), django.core.validators.MaxValueValidator(90)])),
                ('lon', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180), django.core.validators.MaxValueValidator(180)])),
                ('distancia_m', models.PositiveIntegerField(blank=True, help_text='Distancia al centro de geocerca (m)', null=True)),
                ('dentro_geocerca', models.BooleanField(default=False)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='asistencia/checada/foto/')),
                ('nota', models.CharField(blank=True, default='', max_length=255)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checadas_creadas', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checada', to='empleados.empleado')),
                ('ubicacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organigrama.ubicacion')),
            ],
            options={
                'ordering': ('-ts',),
                'indexes': [models.Index(fields=['empleado', 'ts'], name='asistencia__emplead_2127a2_idx'), models.Index(fields=['dentro_geocerca'], name='asistencia__dentro__53553e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Justificacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(db_index=True)),
                ('motivo', models.CharField(max_length=255)),
                ('detalle', models.TextField(blank=True, default='')),
                ('evidencia', models.FileField(blank=True, null=True, upload_to='asistencia/justificaciones/')),
                ('estado', models.CharField(choices=[('PEND', 'Pendiente'), ('APROB', 'Aprobada'), ('RECH', 'Rechazada')], db_index=True, default='PEND', max_length=5)),
                ('resuelto_en', models.DateTimeField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justificaciones_creadas', to=settings.AUTH_USER_MODEL)),
                ('empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='justificaciones', to='empleados.empleado')),
                ('resuelto_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='justificaciones_resueltas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-fecha', '-creado_en'),
                'indexes': [models.Index(fields=['empleado', 'fecha'], name='asistencia__emplead_e191ba_idx'), models.Index(fields=['estado'], name='asistencia__estado_06cb6a_idx')],
            },
        ),
    ]
