# Generated by Django 5.2.7 on 2025-10-18 06:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0001_initial'),
        ('empleados', '0002_empleado_usuario_historicalempleado_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checada',
            name='empleado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checadas', to='empleados.empleado'),
        ),
        migrations.AlterField(
            model_name='checada',
            name='tipo',
            field=models.CharField(choices=[('IN', 'Entrada'), ('OUT', 'Salida')], max_length=4),
        ),
        migrations.AlterField(
            model_name='justificacion',
            name='estado',
            field=models.CharField(choices=[('PEND', 'Pendiente'), ('APROB', 'Aprobado'), ('RECH', 'Rechazado'), ('CANC', 'Cancelado')], db_index=True, default='PEND', max_length=5),
        ),
    ]
