# Generated by Django 5.2.7 on 2025-10-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0002_alter_checada_empleado_alter_checada_tipo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='checada',
            name='actualizado_en',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
