# Generated by Django 5.2.7 on 2025-10-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asistencia', '0003_checada_actualizado_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='justificacion',
            name='estado',
            field=models.CharField(choices=[('PEND', 'Pendiente'), ('APROB', 'Aprobada'), ('RECH', 'Rechazada'), ('CANC', 'Cancelada')], db_index=True, default='PEND', max_length=5),
        ),
    ]
